# Generated by Django 3.0.8 on 2020-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20200816_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosher',
            name='rabbinical_supervision',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
