# Generated by Django 3.0.8 on 2020-08-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_discount'),
        ('venues', '0003_kosher_rabbinical_supervision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centerpiece',
            old_name='external_center_pieces_allowed',
            new_name='outside_centerpieces_allowed',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='centerpieces_cost',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='limitation',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='provide_centerpieces',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='provide_decorations',
        ),
        migrations.AddField(
            model_name='centerpiece',
            name='basic_centerpieces_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centerpiece',
            name='provide_centerpieces',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decoration',
            name='outside_decorations',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decoration',
            name='provide_decorations',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decoration',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
    ]
