# Generated by Django 3.0.8 on 2020-08-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_auto_20200817_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centerpiece',
            name='limitation',
        ),
    ]
