# Generated by Django 3.0.8 on 2020-08-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_remove_centerpiece_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkoption',
            name='beer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='bottom_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='fullopen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='wine',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='wine_beer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
