# Generated by Django 3.0.8 on 2020-08-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_auto_20200819_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkoption',
            old_name='fullopen',
            new_name='full_open',
        ),
        migrations.RenameField(
            model_name='drinkoption',
            old_name='fullopenbar',
            new_name='full_open_bar',
        ),
    ]
