# Generated by Django 3.0.8 on 2020-08-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_discount'),
        ('venues', '0009_auto_20200819_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bartender',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bartender',
            name='limitation',
        ),
        migrations.RemoveField(
            model_name='bartender',
            name='total_bartender_charge',
        ),
        migrations.RemoveField(
            model_name='centerpiece',
            name='basic_centerpieces_cost',
        ),
        migrations.RemoveField(
            model_name='centerpiece',
            name='custom_design_cost',
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='decorations_cost',
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='bottom_only',
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='full_open',
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='wine',
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='wine_beer',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='inhouse_florist_cost',
        ),
        migrations.RemoveField(
            model_name='mealoption',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='limitation',
        ),
        migrations.AddField(
            model_name='bartender',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedbottlefee',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corkfee',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuttingthecakefee',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jewishwedding',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kosher',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photovideo',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seafood',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasting',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waiter',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingcake',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_people', models.IntegerField()),
                ('amount_of_staff', models.IntegerField()),
                ('flat_amount_staff', models.IntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_people', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('flat_fee', models.IntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='OtherStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ManyToManyField(to='venues.Staff')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Venue')),
            ],
        ),
        migrations.AddField(
            model_name='bartender',
            name='staff',
            field=models.ManyToManyField(to='venues.Staff'),
        ),
        migrations.AddField(
            model_name='centerpiece',
            name='basic_pricing',
            field=models.ManyToManyField(related_name='basic_pricing', to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='centerpiece',
            name='custom_pricing',
            field=models.ManyToManyField(related_name='custom_pricing', to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='decorations_pricing',
            field=models.ManyToManyField(to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='pricing',
            field=models.ManyToManyField(to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='flower',
            name='basic_florist_pricing',
            field=models.ManyToManyField(related_name='basic_florist_pricing', to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='flower',
            name='custom_floral_pricing',
            field=models.ManyToManyField(related_name='custom_floral_pricing', to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='foodoption',
            name='pricing',
            field=models.ManyToManyField(to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='mealoption',
            name='pricing',
            field=models.ManyToManyField(to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='rehearsal_ceremony_pricing',
            field=models.ManyToManyField(related_name='rehearsal_ceremony_pricing', to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='rehearsal_dinner_pricing',
            field=models.ManyToManyField(related_name='rehearsal_dinner_pricing', to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='seafood',
            name='pricing',
            field=models.ManyToManyField(to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='tasting',
            name='pricing',
            field=models.ManyToManyField(to='venues.Pricing'),
        ),
        migrations.AddField(
            model_name='waiter',
            name='staff',
            field=models.ManyToManyField(to='venues.Staff'),
        ),
    ]
