# Generated by Django 3.0.8 on 2020-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_auto_20200819_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkoption',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='full_open_bar',
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='full_open_bar',
            field=models.ManyToManyField(to='venues.Pricing'),
        ),
    ]
