# Generated by Django 3.0.8 on 2020-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_auto_20200819_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkoption',
            name='beer_only',
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='beer_only',
            field=models.ManyToManyField(related_name='beer_only', to='venues.Pricing'),
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='bottom_shelf',
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='bottom_shelf',
            field=models.ManyToManyField(related_name='bottom_shelf', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='drinkoption',
            name='full_open_bar',
            field=models.ManyToManyField(related_name='full_open_bar', to='venues.Pricing'),
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='wine_and_beer',
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='wine_and_beer',
            field=models.ManyToManyField(related_name='wine_and_beer', to='venues.Pricing'),
        ),
        migrations.RemoveField(
            model_name='drinkoption',
            name='wine_only',
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='wine_only',
            field=models.ManyToManyField(related_name='wine_only', to='venues.Pricing'),
        ),
    ]
