# Generated by Django 3.0.8 on 2020-08-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_auto_20200819_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='flat_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='flat_amount_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
