# Generated by Django 3.1 on 2020-08-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_auto_20200826_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bartender',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='otherstaff',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='staff',
        ),
        migrations.AddField(
            model_name='bartender',
            name='number_of_bartenders',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bartender',
            name='number_of_guests',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='number_of_guests',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='number_of_other_staff',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waiter',
            name='number_of_guests',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waiter',
            name='number_of_waiter',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
