# Generated by Django 3.1 on 2020-08-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_auto_20200826_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiter',
            old_name='number_of_waiter',
            new_name='number_of_waiters',
        ),
    ]
