# Generated by Django 3.1 on 2020-08-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_discount'),
        ('venues', '0018_auto_20200826_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.IntegerField()),
                ('number_of_waiters', models.IntegerField()),
                ('number_of_bartenders', models.IntegerField()),
                ('number_of_other_staff', models.IntegerField()),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.venue')),
            ],
        ),
        migrations.RemoveField(
            model_name='otherstaff',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Bartender',
        ),
        migrations.DeleteModel(
            name='OtherStaff',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
