# Generated by Django 3.1 on 2020-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0019_auto_20200826_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkoption',
            name='beer_only',
            field=models.ManyToManyField(blank=True, null=True, related_name='beer_only', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='drinkoption',
            name='bottom_shelf',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottom_shelf', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='drinkoption',
            name='full_open_bar',
            field=models.ManyToManyField(blank=True, null=True, related_name='full_open_bar', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='drinkoption',
            name='wine_and_beer',
            field=models.ManyToManyField(blank=True, null=True, related_name='wine_and_beer', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='drinkoption',
            name='wine_only',
            field=models.ManyToManyField(blank=True, null=True, related_name='wine_only', to='venues.Pricing'),
        ),
    ]
