# Generated by Django 3.1 on 2020-08-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0020_auto_20200826_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='cash_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='wire_transfer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='payment_plan_option',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
