# Generated by Django 3.1 on 2020-08-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0021_auto_20200827_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasting',
            name='tastings_offered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centerpiece',
            name='basic_pricing',
            field=models.ManyToManyField(blank=True, null=True, related_name='basic_pricing', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='centerpiece',
            name='custom_design',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centerpiece',
            name='custom_pricing',
            field=models.ManyToManyField(blank=True, null=True, related_name='custom_pricing', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='closedbottlefee',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corkfee',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuttingthecakefee',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='decorations_pricing',
            field=models.ManyToManyField(blank=True, null=True, to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='gluten_free',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='halal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='kosheroption',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='lactose_free',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='sea_food',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='vegan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='vegitarian',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='basic_florist_pricing',
            field=models.ManyToManyField(blank=True, null=True, related_name='basic_florist_pricing', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='custom_floral_design',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='custom_floral_pricing',
            field=models.ManyToManyField(blank=True, null=True, related_name='custom_floral_pricing', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='chicken_and_fish',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='fish_meal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='lamb_meal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='meat_and_chicken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='meat_and_fish',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='meat_meal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='vegan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='vegitarian',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='insuranceandrefund',
            name='cancellation_insurance_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceandrefund',
            name='cancellation_policy_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceandrefund',
            name='insurance_partners',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='bride_reception_room',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='groom_ketubah_room',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='ichud_room',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='seperate_dancing_option',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='seperate_seating_option',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kosher',
            name='beit_yoseph',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kosher',
            name='chalav_yisrael',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kosher',
            name='glatt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kosher',
            name='kemach_yisrael',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealoption',
            name='buffet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealoption',
            name='sitdown',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overnight',
            name='bulk_rooms_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overnight',
            name='hotel_partners',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overnight',
            name='room_costs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='car_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='parking_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='valet_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='accept_check',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='accept_credit_card',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cash_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='wire_transfer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photovideo',
            name='inhouse_photography_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photovideo',
            name='inhouse_video_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='rehearsal_ceremony_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='rehearsal_ceremony_pricing',
            field=models.ManyToManyField(blank=True, null=True, related_name='rehearsal_ceremony_pricing', to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='rehearsal_dinner_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='crab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='lobster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='oysters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='sea_food_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='shrimp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='tasting_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuedetail',
            name='outside_catering',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuedetail',
            name='recommended_tip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingcake',
            name='five_layer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingcake',
            name='four_layer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingcake',
            name='three_layer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingcake',
            name='two_layer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
