# Generated by Django 3.1 on 2020-08-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0023_generalcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontact',
            name='contact_person',
            field=models.CharField(default=False, max_length=150),
            preserve_default=False,
        ),
    ]
