# Generated by Django 3.1 on 2020-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0024_generalcontact_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedbottlefee',
            name='limitation',
        ),
        migrations.RemoveField(
            model_name='cuttingthecakefee',
            name='limitation',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='limitation',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='cake_cutting_fee',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='corkage_fee',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='offer_tastings',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='outside_florist',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='outside_photography',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='outside_videography',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='payment_plans',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='provide_bartenders',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='provide_waiters',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='provide_wedding_cake',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='unopen_bottle_fee',
        ),
        migrations.AddField(
            model_name='corkfee',
            name='corkage_fee',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuttingthecakefee',
            name='cake_cutting_fee',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='outside_florist',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photovideo',
            name='outside_photography',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photovideo',
            name='outside_videography',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingcake',
            name='provide_wedding_cake',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='centerpiece',
            name='basic_pricing',
        ),
        migrations.AddField(
            model_name='centerpiece',
            name='basic_pricing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='centerpiece',
            name='custom_pricing',
        ),
        migrations.AddField(
            model_name='centerpiece',
            name='custom_pricing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='decoration',
            name='decorations_pricing',
        ),
        migrations.AddField(
            model_name='decoration',
            name='decorations_pricing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='flower',
            name='basic_florist_pricing',
        ),
        migrations.AddField(
            model_name='flower',
            name='basic_florist_pricing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='flower',
            name='custom_floral_pricing',
        ),
        migrations.AddField(
            model_name='flower',
            name='custom_floral_pricing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
