# Generated by Django 3.1 on 2020-08-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_discount'),
        ('venues', '0026_auto_20200827_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='VenueImage',
        ),
    ]
