# Generated by Django 3.1 on 2020-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0027_auto_20200827_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venue-images/'),
        ),
    ]
