# Generated by Django 3.1 on 2020-08-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0028_auto_20200827_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedbottlefee',
            name='closed_bottle_fee',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='candles',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='ceremony_reception_seperate_rooms',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='ceremony_seating_provided',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='coat_room',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='designated_smoking_area',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='indoor_smoking',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='provide_booster_seats',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='provide_place_cards',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='secure_room',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='sparklers',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='tip_included',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='wheelchair_accessible',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='centerpiece',
            name='custom_design',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centerpiece',
            name='provide_centerpieces',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='corkfee',
            name='corkage_fee',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='cuttingthecakefee',
            name='cake_cutting_fee',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='outside_decorations',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='provide_decorations',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='gluten_free',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='halal',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='kosheroption',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='lactose_free',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='sea_food',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='vegan',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietaryoption',
            name='vegitarian',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flower',
            name='custom_floral_design',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flower',
            name='outside_florist',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='indooroptions',
            name='indoor_ceremony',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='indooroptions',
            name='indoor_dancing',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='indooroptions',
            name='indoor_reception',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='insuranceandrefund',
            name='cancellation_insurance',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='bride_reception_room',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='groom_ketubah_room',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='ichud_room',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='seperate_dancing_option',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewishwedding',
            name='seperate_seating_option',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kosher',
            name='beit_yoseph',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kosher',
            name='chalav_yisrael',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kosher',
            name='glatt',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kosher',
            name='kemach_yisrael',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kosher',
            name='rabbinical_supervision',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealoption',
            name='buffet',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealoption',
            name='sitdown',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outdooroptions',
            name='outdoor_ceremony',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='outdooroptions',
            name='outdoor_dancing',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='outdooroptions',
            name='outdoor_reception',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='parking',
            name='onsite_parking',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='parking',
            name='valet',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='accept_check',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='accept_credit_card',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cash_only',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='wire_transfer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='payment_plan_option',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='photovideo',
            name='outside_photography',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='photovideo',
            name='outside_videography',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='rainbackup',
            name='electric_generator',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='rainbackup',
            name='inside_space',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='rainbackup',
            name='tents_or_canopies',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='rehearsal_ceremonies',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='rehearsal_dinners',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='crab',
            field=models.IntegerField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seafood',
            name='lobster',
            field=models.IntegerField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seafood',
            name='oysters',
            field=models.IntegerField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seafood',
            name='sea_food_package',
            field=models.IntegerField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seafood',
            name='shrimp',
            field=models.IntegerField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasting',
            name='tastings_offered',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venuedetail',
            name='outside_catering',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
    ]
