# Generated by Django 3.1 on 2020-08-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0029_auto_20200827_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerpiece',
            name='outside_centerpieces_allowed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='crab',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='lobster',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='oysters',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='sea_food_package',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='shrimp',
            field=models.IntegerField(),
        ),
    ]
