# Generated by Django 3.1 on 2020-08-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_discount'),
        ('venues', '0030_auto_20200827_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='indooroptions',
            name='venue',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='indooroptions', to='accounts.venue'),
            preserve_default=False,
        ),
    ]
