# Generated by Django 3.1 on 2020-09-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0031_indooroptions_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='people_per_table',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arrivalsetup',
            name='hours_preevent_arrival',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arrivalsetup',
            name='hours_preevent_setup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuedetail',
            name='deposit_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuedetail',
            name='min_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuedetail',
            name='non_refundable_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
