# Generated by Django 3.1 on 2020-09-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0032_auto_20200902_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='tip_included',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
