# Generated by Django 3.1 on 2020-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0033_auto_20200902_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='payment_plan_option',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
