# Generated by Django 3.1 on 2020-09-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0034_auto_20200902_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodoption',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='mealoption',
            name='venue',
        ),
        migrations.AddField(
            model_name='mealoption',
            name='food_option',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='venues.foodoption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='chicken_and_fish',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='fish_meal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='lamb_meal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='meat_and_chicken',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='meat_and_fish',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='meat_meal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='vegan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='vegitarian',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
