# Generated by Django 3.1 on 2020-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0035_auto_20200903_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seafood',
            name='dietary',
        ),
        migrations.AlterField(
            model_name='seafood',
            name='crab',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='lobster',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='oysters',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='sea_food_package',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='shrimp',
            field=models.BooleanField(),
        ),
    ]
