# Generated by Django 3.1 on 2020-09-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0038_auto_20200903_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealoption',
            name='buffet',
        ),
        migrations.RemoveField(
            model_name='mealoption',
            name='sitdown',
        ),
        migrations.AddField(
            model_name='mealoption',
            name='meal_option',
            field=models.BooleanField(choices=[(True, 'Sit Down'), (False, 'Buffet')], default=False),
            preserve_default=False,
        ),
    ]
