# Generated by Django 3.1 on 2020-09-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_discount'),
        ('venues', '0039_auto_20200906_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodoption',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='mealoption',
            name='food_option',
        ),
        migrations.AddField(
            model_name='foodoption',
            name='meal_option',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='venues.mealoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealoption',
            name='venue',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.venue'),
            preserve_default=False,
        ),
    ]
