# Generated by Django 3.1 on 2020-09-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_discount'),
        ('venues', '0042_auto_20200906_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkoption',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.venue'),
        ),
    ]
