# Generated by Django 3.1 on 2020-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0044_remove_rainbackup_inside_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdaycontact',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='generalcontact',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
