# Generated by Django 3.1 on 2020-09-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0045_auto_20200908_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='photovideo',
            name='inhouse_photographer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photovideo',
            name='inhouse_videographer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
    ]
