# Generated by Django 3.1 on 2020-09-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0046_auto_20200908_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingcake',
            old_name='five_layer',
            new_name='people_fed',
        ),
        migrations.RemoveField(
            model_name='weddingcake',
            name='four_layer',
        ),
        migrations.RemoveField(
            model_name='weddingcake',
            name='three_layer',
        ),
        migrations.RemoveField(
            model_name='weddingcake',
            name='two_layer',
        ),
        migrations.AddField(
            model_name='weddingcake',
            name='cake_option',
            field=models.CharField(choices=[('two_layer', 'Two Layer Cake'), ('three_layer', 'Three Layer Cake'), ('four_layer', 'Four Layer Cake'), ('five_layer', 'Five Layer Cake')], default=False, max_length=50),
            preserve_default=False,
        ),
    ]
