# Generated by Django 3.1 on 2020-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0047_auto_20200908_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingcake',
            name='provide_wedding_cake',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
