# Generated by Django 3.1 on 2020-09-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200907_1404'),
        ('venues', '0050_auto_20200909_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingcake',
            name='provide_wedding_cake',
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='provide_wedding_cake',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingcake',
            name='pricing',
            field=models.ManyToManyField(to='venues.Pricing'),
        ),
        migrations.AlterField(
            model_name='weddingcake',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='accounts.venue'),
        ),
    ]
