# Generated by Django 3.1 on 2020-09-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0051_auto_20200909_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingcake',
            name='people_fed',
        ),
    ]
