# Generated by Django 3.1 on 2020-09-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0052_remove_weddingcake_people_fed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuedetail',
            name='min_fee',
        ),
    ]
