# Generated by Django 3.1 on 2020-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0054_auto_20200909_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuedetail',
            name='outside_catering',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
